### PR TITLE
WIP: encapsulate all metadata about a given field in a single Field object

### PR DESCRIPTION
**Pull request by apdavison**
This allows generic implementations of the `__init__`, `_build_data()`, `from_kg_instance()` and `__repr__` methods while also providing better type and value checking.

This is a work-in-progress. Only a couple of classes have been converted so far.

### CODE REVIEW

**Comment by apdavison** [comment]
ah, I hadn't intended for this to be merged yet, I just wanted comments/feedback. "WIP" in the title is for "work in progress" 😉 

Please could you and @GMattheisen check this doesn't break any of your scripts/notebooks?

**Comment by yzerlaut** [comment]
Yes, I wanted to access and play with it, so doing the merge enabled it, but that's not the right way to do this, right ? I should have added your apdavison repo as an upstream source and fetched your branch, not getting it through the hbp repo... right ?

It does break some scripts, 
e.g. the "python manage.py kg_migration" running the  "_getPersons_and_migrate()" function breaks with the error:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/yann/anaconda3/envs/dev/lib/python3.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/yann/anaconda3/envs/dev/lib/python3.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/yann/anaconda3/envs/dev/lib/python3.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/yann/anaconda3/envs/dev/lib/python3.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "../model_validation_api/management/commands/kg_migration.py", line 683, in handle
    self._getPersons_and_migrate()
  File "../model_validation_api/management/commands/kg_migration.py", line 337, in _getPersons_and_migrate
    self._create_person_in_kg(auth)
  File "../model_validation_api/management/commands/kg_migration.py", line 299, in _create_person_in_kg
    self._save_person_in_KG(person_object[0].first_name,person_object[0].last_name, person_object[0].email)
  File "../model_validation_api/management/commands/kg_migration.py", line 366, in _save_person_in_KG
    if not person.exists(NAR_client):
  File "/Users/yann/anaconda3/envs/dev/lib/python3.7/site-packages/fairgraph/base.py", line 296, in exists
    response = client.filter_query(self.__class__.path, query_filter, context)
  File "/Users/yann/anaconda3/envs/dev/lib/python3.7/site-packages/fairgraph/base.py", line 80, in path
    raise ValueError("namespace not set")
ValueError: namespace not set
```
It's link to the changes in base.py, I attach the diff
[diff.txt](https://github.com/HumanBrainProject/fairgraph/files/3631917/diff.txt)

If you need to run stuff. The commit ID of a functional version is:
89a62b5e1016cb4d2fcadff3ee166938c00de44d

**Comment by apdavison** [comment]
> I should have added your apdavison repo as an upstream source and fetched your branch, not getting it through the hbp repo... right ?

yes, correct

**Comment by apdavison** [comment]
> ValueError: namespace not set

yes, this will appear in all scripts using the `core` module. In general, you should carefully review which namespace is being used, and ideally set this explicitly at the beginning of each script, either directly on the classes you're using, or per-module using the `use_namespace()` function in each module.

**Pull request merged**
